### recuperar todas las peliculas
GET http://localhost:1234/movies

### recuperar una pelicula por id
GET http://localhost:1234/movies/6d3b3f7c-74bd-11ef-a170-047c16877420

### recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=crime


### crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "Who Am I: Kein System ist sicher",
  "year": 2014,
  "director": "Baran bo Odar",
  "duration": 102,
  "poster": "https://m.media-amazon.com/images/I/71kEzbj7nIL._AC_SY679_.jpg",
  "rate": 7.6,
  "genre": [
    "Crime"
  ]
}

### Actualizar una pelicula

PATCH http://localhost:1234/movies/6d3b3f7c-74bd-11ef-a170-047c16877420
Content-Type: application/json

{
  "title": "Who Am I"
}

### Borrar una pelicula 

DELETE http://localhost:1234/movies/cdc28e6f-74bc-11ef-a170-047c16877420
